---
# network
host: '0.0.0.0'
port: 5566

# map
# map_file: 'data/maps/map_empty_1cm.png'
# map_file: 'data/maps/map_complex_1cm.png'
map_file: 'data/maps/test_5cm.png'
# map_scale: 0.01
map_scale: 0.05  # for test_5cm

# display
robot_radius: 2  # 10

# simulation
start_pose:
  x: 2.5
  y: 1.0
  z: 0.5
use_noisy_pose: off
robot_phy_length: 0.32
pos_noise_stddev: 0.05

# localization proxy
proxy_real_robot: off
proxy_host: 'localhost'
proxy_port: 5567

# logging
log_level: 'debug'

# clues
clues:
  - clue_id: 2
    trigger:
      x: 2.5
      y: 1.0
      r: 0.5
    location:
      x: 2.5
      y: 1.8
    audio_file: 'data/audio/SM4_F48_A0100.wav'
  - clue_id: 3
    trigger:
      x: 1.3
      y: 1.3
      r: 0.3
    location:
      x: 2.3
      y: 2.5
    audio_file: 'data/audio/SM4_F48_A0100.wav'

# targets
targets:
  - target_id: 10
    trigger:
      x: 2.5
      y: 1.8
      r: 0.2
    image_file: 'data/imgs/fallen_person.jpeg'
